"""
send_expert_report endpoint — added to projects_bp

POST /api/v1/projects/<id>/send-expert-report
Body:
{
  "expert_ids": ["uuid1", ...],      // selected accepted experts
  "recipient": "myself" | "client",  // who to send to
  "rates": { "uuid1": 150, ... }     // client rate per expert (USD/hr)
}

- "myself"  → sends to the logged-in HasamexUser's email (from JWT)
- "client"  → sends to all User emails mapped via project.poc_user_id +
              any Users whose client_id matches project.client_id
- Only Accepted-status experts are included in the report.

Email body per expert (numbered Expert#01 … Expert#0N):
  - Bio
  - Employment History
  - Availability (timezone + form-submitted slots)
  - Project Questions & Expert Answers (from ProjectFormSubmission)
  - Client Rate (from request body)
"""

from flask import Blueprint, request, jsonify, current_app
import threading
from extensions import db
from auth import decode_token
from models import Project, Expert, ProjectFormSubmission, HasamexUser, User


# ─────────────────────────────────────────────────────────────────────────────
# HTML Email builder
# ─────────────────────────────────────────────────────────────────────────────

def _build_expert_report_text(project, experts_data):
    """
    Build a structured plain-text email containing all selected accepted experts' details.
    """
    p_title = project.project_title or project.title or "Project"
    p_code  = f"PRJ-{project.project_id}"
    count   = len(experts_data)

    lines = []
    lines.append("=" * 60)
    lines.append(f"{p_title.upper()} | HASAMEX EXPERT REPORT")
    lines.append(f"Project Code: {p_code}")
    lines.append(f"Experts:      {count} Accepted Expert(s)")
    lines.append("=" * 60)
    lines.append("")
    lines.append(f"This report contains profiles of {count} accepted expert(s) for your review.")
    lines.append("")

    for idx, ed in enumerate(experts_data, 1):
        expert = ed["expert"]
        sub    = ed["submission"]
        rate   = ed["rate"]
        
        name   = f"{expert.first_name or ''} {expert.last_name or ''}".strip() or "Expert"
        title  = expert.title_headline or "Professional"
        bio    = expert.bio or "No bio available."
        tz     = expert.timezone or (expert.rel_location.timezone if expert.rel_location else None) or "Unknown"

        lines.append(f"--- EXPERT #{idx:02d} ---")
        lines.append(f"Title: {title}")
        lines.append("")
        lines.append("BIOGRAPHY :")
        lines.append(bio)
        lines.append("")

        lines.append("EMPLOYMENT HISTORY :")
        if expert.experiences:
            for exp in expert.experiences:
                yr = f"{exp.start_year or '??'} - {exp.end_year or 'Present'}"
                lines.append(f"• {exp.role_title} @ {exp.company_name} ({yr})")
        else:
            lines.append("No employment history on file.")
        lines.append("")

        lines.append("AVAILABILITY :")
        lines.append(f"Timezone: {tz}")
        if sub and sub.availability_dates:
            slots = sub.availability_dates if isinstance(sub.availability_dates, list) else []
            if slots:
                for slot in slots:
                    lines.append(f"• {slot.get('date', '')} | {slot.get('startTime', '')} - {slot.get('endTime', '')}")
            else:
                lines.append("No slots submitted.")
        else:
            lines.append("No form submission yet.")
        lines.append("")

        lines.append("PROJECT Q&A :")
        if sub and sub.project_qns_ans:
            qas = sub.project_qns_ans if isinstance(sub.project_qns_ans, dict) else {}
            for q, a in qas.items():
                lines.append(f"Q: {q}")
                lines.append(f"A: {a}")
                lines.append("")
        else:
            lines.append("No project Q&A submitted.")
            lines.append("")

        lines.append("CLIENT RATE :")
        if rate:
            lines.append(f"USD {rate:,.0f}/hr")
        else:
            lines.append("Rate not specified")
        
        lines.append("-" * 40)
        lines.append("")

    lines.append("CONFIDENTIAL: This is a confidential expert report generated by Hasamex HUB.")
    lines.append("Please do not forward externally.")

    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# Background sender
# ─────────────────────────────────────────────────────────────────────────────

def _bg_send_expert_report(app, project_id, expert_ids, rates, recipient_emails, sender_email):
    """Background thread: build HTML report and send email."""
    with app.app_context():
        from services.mailer import send_email
        import logging

        project = Project.query.get(project_id)
        if not project:
            return

        experts = Expert.query.filter(Expert.id.in_(expert_ids)).all()
        if not experts:
            return

        experts_data = []
        for expert in experts:
            sub = ProjectFormSubmission.query.filter_by(
                project_id=project_id, expert_id=expert.id
            ).first()
            rate = rates.get(str(expert.id)) or rates.get(expert.id) or None
            if rate:
                try:
                    rate = float(rate)
                except (ValueError, TypeError):
                    rate = None
            experts_data.append({"expert": expert, "submission": sub, "rate": rate})

        p_title = project.project_title or project.title or "Project"
        subject = f"Expert Report — {p_title} ({len(experts_data)} Accepted Expert{'s' if len(experts_data) != 1 else ''})"

        try:
            text = _build_expert_report_text(project, experts_data)
            send_email(
                to=recipient_emails,
                subject=subject,
                text=text,
                reply_to=sender_email,
            )
            logging.info(f"Expert report sent to {recipient_emails} for project {project_id}")
        except Exception as e:
            logging.error(f"Failed to send expert report: {e}")


# ─────────────────────────────────────────────────────────────────────────────
# Route registration helper (call from projects.py)
# ─────────────────────────────────────────────────────────────────────────────

def register_send_expert_report(projects_bp):
    """Register the send-expert-report route on the provided blueprint."""

    @projects_bp.route('/<int:project_id>/send-expert-report', methods=['POST'])
    def send_expert_report(project_id):
        """
        POST /api/v1/projects/<id>/send-expert-report
        Body: { expert_ids, recipient, rates }
        """
        project = Project.query.get_or_404(project_id)
        data = request.get_json() or {}

        expert_ids = data.get("expert_ids") or []
        recipient  = (data.get("recipient") or "myself").lower()
        rates      = data.get("rates") or {}    # { expert_id: rate }

        if not expert_ids:
            return jsonify({"error": "No expert_ids provided"}), 400
        if recipient not in ("myself", "client"):
            return jsonify({"error": "recipient must be 'myself' or 'client'"}), 400

        # ── Resolve sender from JWT ──
        sender_email = None
        current_user = None
        try:
            auth = request.headers.get("Authorization") or ""
            if auth.startswith("Bearer "):
                claims = decode_token(auth.split(" ", 1)[1].strip())
                user_id = claims.get("user_id")
                sender_email = claims.get("email")
                if user_id:
                    current_user = HasamexUser.query.get(user_id)
                    if current_user:
                        sender_email = current_user.email
        except Exception:
            pass

        # ── Resolve recipient emails ──
        if recipient == "myself":
            if not sender_email:
                return jsonify({"error": "Could not determine your email. Please log in again."}), 401
            recipient_emails = [sender_email]

        else:  # "client"
            emails = set()

            # 1. PoC users (from users table)
            if project.poc_user_ids:
                poc_users = User.query.filter(User.user_id.in_(project.poc_user_ids)).all()
                for poc in poc_users:
                    if poc.email:
                        emails.add(poc.email.strip())

            if not emails:
                return jsonify({
                    "error": "No PoC client email addresses found for this project. "
                             "Ensure the project has PoC users assigned with valid emails."
                }), 400

            recipient_emails = list(emails)

        # ── Filter to Accepted experts only ──
        accepted_ids = set(project.accepted_expert_ids or [])
        filtered_ids = [eid for eid in expert_ids if str(eid) in accepted_ids]

        if not filtered_ids:
            return jsonify({
                "error": "None of the selected experts have Accepted status. "
                         "Only Accepted experts are included in the expert report."
            }), 400

        # ── Fire background email ──
        app = current_app._get_current_object()
        threading.Thread(
            target=_bg_send_expert_report,
            args=(app, project_id, filtered_ids, rates, recipient_emails, sender_email),
            daemon=True,
        ).start()

        return jsonify({
            "message": f"Expert report is being sent to {', '.join(recipient_emails)}.",
            "expert_count": len(filtered_ids),
            "recipients": recipient_emails,
        }), 200
